### ISSUE TITLE
v3.0 Tracking

### ISSUE THREAD

**Issue by jstcki** [interactivethings/eslint-config-interactivethings#8]
- [ ] Bump eslint to v2
- [ ] Bump eslint-plugin-react to v4
- [ ] Bump babel-eslint to v6 (once it works with eslint v2)
- [ ] Add eslint-plugin-immutable (see #7)

**Comment by jstcki** [comment]
Closing again, using the 3.0 milestone instead to group individual issues.
